### PR TITLE
Auth merge

### PR DESCRIPTION
**Pull request by SahilTikale**
@zenhack 
Use this patch, discard the #7

### CODE REVIEW

**Comment by zenhack** [comment]
@SahilTikale, you missed the `node_register` calls in `tests/stress.py`. Please fix. Otherwise looks good.

**Comment by SahilTikale** [comment]
Hi I did this patch, because the last one was done with using any merge_commit. I did not know about it, until today when @henn explained it to me.

To keep things clean I made a new patch. 

Also I saw your comment, on https://github.com/CCI-MOC/haas/pull/551
Should I include it here.

**Comment by SahilTikale** [comment]
After my IPMI-driver PR got merged, strangely it is missing the obmTests I wrote, that you reviewed and approved. 

Should I include those in this patch.

**Comment by zenhack** [comment]
Merged.

Re: opening a new pr, makes sense.

Re: missing tests, you can deal with those separately; the auth branch is mergeable again, so that's a separate concern.

Thanks for doing this.

**Comment by henn** [comment]
@SahilTikale - would you mind running the deployment tests on this
branch again just to be sure?

Thanks!

**Comment by SahilTikale** [comment]
ok, no problem.

**Comment by SahilTikale** [comment]
Passes all deployment tests

**Pull request merged**
