### PR TITLE
Suggested docs changes for #491

### PR DESCRIPTION
**Pull request by henn**
This contains suggested doc changes for CCI-MOC/haas#491

### CODE REVIEW

**Comment by henn** [comment]
Please don't merge this yet; still making changes.

**Comment by zenhack** [comment]
These look good so far. Let me know when you're done.

**Comment by henn** [comment]
Ready to review

**Comment by zenhack** [comment]
Per the comment I made on the commit itself, I don't understand what 4bc35ca is for, but otherwise this looks good. Can you explain that one?

**Comment by henn** [comment]
If you really don't want it, I can create a separate PR. After I figured out the regexp (see the commit message for 4bc35ca94bf7bc5a08224d1ca7435547f429dd35), it's pretty easy to re-do.

**Comment by zenhack** [comment]
I just don't understand what you were trying to do. No need to create a separate pr; I can just merge the other two commits locally.

**Comment by zenhack** [comment]
Ah, didn't see your response. I think I'll leave off the last commit and merge the rest; github seems happy, and it looks better in source form.

**Comment by zenhack** [comment]
Okay, merged the first two via the  cli. I'm going to close.

**Pull request closed without merging**
